### model
model_name_or_path: /dockerdata/llm_models/Qwen3.5-27B
trust_remote_code: true

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: full
# lora_target: all
# lora_rank: 8
deepspeed: examples/deepspeed/ds_z2_config.json

###logging
run_name: Qwen3.5-27B_mix-attribution_full_experiment

### dataset
dataset: taiji_train_data
template: qwen3_5_nothink
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16 
dataloader_num_workers: 8

### output
output_dir: saves/
logging_steps: 1
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_total_limit: 30          # 限制 checkpoint 数量
report_to: tensorboard  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
max_grad_norm: 1.0          # 梯度裁剪，防止训练崩溃
gradient_checkpointing: true             # 显存爆炸必须开
flash_attn: fa2 

### eval
val_size: 0.1 #2000
per_device_eval_batch_size: 3
eval_strategy: steps
eval_steps: 200
### 关键配置：保存 best model
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false





